language: generic

install:
  - nvm use 11.0.0
  - npm --version
  - node --version
  - mkdir ../backup
  - mv * ../backup
  - git clone https://github.com/kahverengi001/portfolio-backend.git portfolio-back-end
  - cd portfolio-back-end
  - mv * ../
  - cd ..
  - rm -rf portfolio-back-end
  - ./gradlew build
  - mkdir portfolio-front-end
  - mv ../backup/* portfolio-front-end
  - rm -rf ../backup
  - cd portfolio-front-end
  - npm install
  - npm run build
  - cp -avr public ../public
  - cd ..
  - rm -rf portfolio-front-end

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: $HEROKU_API_KEY
    strategy: api
    app: kahverengi-portfolio
    on:
      branch: master
  - provider: heroku
    skip_cleanup: true
    api_key: $HEROKU_API_KEY
    strategy: api
    app: test-kahverengi-portfolio
    on:
      branch: staging